### ISSUE TITLE
Return to Sentiment Home after creating or editing a model

### ISSUE THREAD

**Issue by pppina** [P1514/Diversity#12]
When user submits the Opinion Model for creation/update, she should be re-directed to Sentiment Home.

**Comment by P1514** [comment]
Enhancement: when new iframe is created there should exist an option for the user to return to home or keep creating models

**Comment by fmano** [comment]
Opinion Model page now redirects to Sentiment Home after create/update. Issue will stay open until the option to stay or leave is added.

**Comment by fmano** [comment]
Done
