### ISSUE TITLE
No collaboration: ao adicionar o user admin admin ao my team e de seguida remove-lo este não fica visível nem na tabela my team na na tabela available members (só ocorre especificamente para este user)

### ISSUE THREAD

**Issue by P1514** [P1514/Diversity#129]

**Comment by P1514** [comment]
Acontece o mesmo para todos os primeiro users que tiverem na lista, por exemplo se o primeiro utilizador da lista for o test2 e se adicionar ao remover não volta a aparecer a não ser que se faça refresh à tabela (mudar opções de utilizadores a mostrar)

**Comment by fmano** [comment]
Done
