### ISSUE TITLE
Extraction Page

### ISSUE THREAD

**Issue by P1514** [P1514/Diversity#136]
-> Criar forma de remover a seleção da tagcloud
-> Melhorar a forma de fechar janela depois de abrir a opinion, talvez a opção complementar de carregar no ESC para fechar ( o Paulo spamma esta tecla)

**Comment by P1514** [comment]
Media Wiki Radio Button

**Comment by fmano** [comment]
Media wiki radio button fixed

**Comment by P1514** [comment]
Media Wiki Radio Button not fixed.
Botão Back passa a redirecionar para a pagina anterior do histórico.
Tooltip gráfico Top_middle para mostrar identificar que aqui já são posts e não opinions.
