### ISSUE TITLE
Ainda no extraction page

### ISSUE THREAD

**Issue by P1514** [P1514/Diversity#137]
Gauge -> Ausência de dados fica a 50
Passar a ser o ultimo sentimento calculado

**Comment by fcrsilva** [comment]
Working on it

**Comment by P1514** [comment]
Verificar que a TagCloud está a funcionar como é suposto, se o que realmente aparece na positive vem de opinions > 50, Exemplo (Worst aparece na cloud positiva)

**Comment by fcrsilva** [comment]
![opinions_contaning_love](https://user-images.githubusercontent.com/23050194/31180134-b99d7338-a915-11e7-97ed-cd611f86d318.jpeg)
![opinions_contaning_wooooooow](https://user-images.githubusercontent.com/23050194/31180135-b9d92720-a915-11e7-9605-4615664336c8.jpeg)
![opinions_containing_winters](https://user-images.githubusercontent.com/23050194/31180136-b9e20296-a915-11e7-8f54-ec4d9b928885.jpeg)
![opinions_containing_zareo](https://user-images.githubusercontent.com/23050194/31180137-b9eb7290-a915-11e7-987c-7dff8fbb69dd.jpeg)

Sim parece estar bem, todas as palabras que testei bateu certo, já o tamanho das mesma penso que não esteja como é suposto.

**Comment by fcrsilva** [comment]
![image](https://user-images.githubusercontent.com/23050194/31181287-d8af0680-a918-11e7-836c-e7266e52add8.png)
Em relação à palavra worse. Realmente a polarity destas opinions é positiva.
