### ISSUE TITLE
Extraction Page URGENTE

### ISSUE THREAD

**Issue by P1514** [P1514/Diversity#150]
Questão dos Gráficos.

Então após andar aqui a chafurdar no código, como por em lama. Cheguei à conclusão do seguinte. Tudo está a funcionar, apenas não como é suposto.

Ponto 1 ) Quando o gráfico é clicado envia algo do genero filter month Feb, não pode visto que pode ter anos e dias e etc. Possivel ser necessário mudar no backend.
Ponto 2 ) O problema da seleção vem daqui ora então, quando o reach é enviado temos dados de 1 até à row 200, quando é o sentiment temos dados de 1 até 27000(ish). Dou uma dica, tem a ver com enviar todos os valores com -1 para quando não há dados.

**Comment by fmano** [comment]
Front-end alterado para passar a enviar Day, Month e Year em vez de apenas Month

**Comment by fmano** [comment]
Isto está fixed, mas não vou fechar porque os gráficos não estão a coincidir ( o reach (middle) acaba muito depois do sentiment(right) )

**Comment by P1514** [comment]
Is it fixed?

**Comment by fmano** [comment]
Its fixed
