### ISSUE TITLE
Product List

### ISSUE THREAD

**Issue by P1514** [P1514/Diversity#201]
Wasn't it live?

**Comment by fmano** [comment]
Acrescentei um botão para refresh de produtos no model creation e um para refresh de users no collaboration.
O botão dos produtos está testado e a funcionar; falta testar o botão de users (se alguem puder testar agradeço)

**Comment by fmano** [comment]
This is the same issue, right?
![image](https://user-images.githubusercontent.com/6649133/34150510-6f249a22-e4a0-11e7-8def-7fce9e499302.png)
