### ISSUE TITLE
Tag Cloud GEOX

### ISSUE THREAD

**Issue by P1514** [P1514/Diversity#202]
Wierd result please check

**Comment by P1514** [comment]
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/20281498/33718203-7df1a428-db54-11e7-8eb3-ce67c3a1db13.png">

This is what shows on positive. On Negative it works fine

**Comment by fmano** [comment]
![image](https://user-images.githubusercontent.com/6649133/33829565-c0cbb1fa-de68-11e7-9e9a-6c8d73c853d8.png)
Fixed
