### ISSUE TITLE
Modelling Refresh Products

### ISSUE THREAD

**Issue by P1514** [P1514/Diversity#204]
The entire PSS database should be refreshed, so the button should be besides the pss field, I was thinking more about a button like 
![image](https://user-images.githubusercontent.com/20281498/33944202-58c6992e-e013-11e7-80a0-b524befa58de.png)

Smaller and fitting the theme. Nonetheless it works

**Comment by fmano** [comment]
![image](https://user-images.githubusercontent.com/6649133/34150330-f456d206-e49f-11e7-96c8-da1d7d302f1e.png)
Done
