### ISSUE TITLE
Fetching snapshot URL

### ISSUE THREAD

**Issue by P1514** [P1514/Diversity#68]
An endpoint must be created to provide snapshots related to a specific PSS. Example: Outside tool sends a request to Sentiment Analysis asking for information on PSS: "D522-1", Sentiment Analysis must answer accordingly with the list of snapshots for that specific PSS, snapshots regarding the same range of dates "redundant" should be filtered out of the answer. This requires both backend and front-end implementation. Front-end converts the snapshots existing from normal path to URL. Implementation should be done in a RESTFul request like operation.

**Comment by fcrsilva** [comment]
Implemented in the backend

**Comment by fmano** [comment]
implemented in frontend
