### ISSUE TITLE
Loading Iframe

### ISSUE THREAD

**Issue by P1514** [P1514/Diversity#9]
Add loading iframe like this 
![image](https://cloud.githubusercontent.com/assets/20281498/20520998/ff0938bc-b0a0-11e6-82f1-cc6aa213cd7a.png)

**Comment by fmano** [comment]
Done (added to opinion extraction page)
![loading](https://cloud.githubusercontent.com/assets/6649133/21605974/5ddac33c-d1a4-11e6-96e7-2c1b4dc966ed.png)

**Comment by fmano** [comment]
Still need to switch alert popups to frames like the loading frame
